spring:
  # 数据源
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/forest_blog?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&useTimezone=true&serverTimezone=Asia/Shanghai
      username: root
      password: *****
      initial-size: 5
      min-idle: 5
      max-active: 100
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'ok' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      aop-patterns: com.hessianhealth.phoenix.information.service.*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/actuator/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
      filter:
        stat:
          log-slow-sql: true
